# Generated by Django 4.1.2 on 2022-11-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, null=True)),
                ('prenom', models.CharField(max_length=60, null=True)),
                ('numéro', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
    ]
